name: Scheduled QA execution

on:
  workflow_dispatch:

jobs:
  call-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger QA API execution
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/test_action_execution.yaml/dispatches \
            -d '{"ref":"main", "inputs":{"chrome":"true", "edge":"true", "test_options":"All", "environment":"QA"}}'