name: Run Selenium Tests and publish report experimental

on:
  workflow_call:
    inputs:
      chrome:
        type: boolean
      edge:
        type: boolean
      test_options:
        type: string
      environment:
        type: string
  workflow_dispatch:
    inputs:
      chrome:
        description: 'Include Chrome'
        required: false
        default: true
        type: boolean
      edge:
        description: 'Include Edge'
        required: false
        default: false
        type: boolean

      test_options:
        description: 'Select test options'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Login'
          - 'Logout'

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - 'QA'
          - 'UAT'

jobs:
  chrome-test:
    name: Run Chrome tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=chrome" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Push results
        uses: Simeon-Zografov/build-allure-report-action/.github/actions/push-individual-report@main
        if: always()
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          browser: ${{ env.BROWSERS }}
          number-of-browsers: 2

  edge-test:
    name: Run Edge tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edge == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=edge" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Push results
        uses: Simeon-Zografov/build-allure-report-action/.github/actions/push-individual-report@main
        if: always()
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          browser: ${{ env.BROWSERS }}
          number-of-browsers: 2

  aggregate:
    name: Generate report
    needs: [ chrome-test, edge-test ]
    if: always()
    runs-on: ubuntu-latest
    steps:

      - name: Run report publish action
        uses: Simeon-Zografov/build-allure-report-action/.github/actions/build-report@main
        with:
          branch: gh_pages
          env_name: ${{ github.event.inputs.environment }}
          report_id: ${{ github.run_number }}
          keep_reports: 10

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: gh_pages
