name: Run Selenium Tests and publish report

on:
  workflow_dispatch:
    inputs:
      chrome:
        description: 'Include Chrome'
        required: false
        default: true
        type: boolean
      edge:
        description: 'Include Edge'
        required: false
        default: false
        type: boolean

      test_options:
        description: 'Select test options'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Login'
          - 'Logout'

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - 'QA'
          - 'UAT'

jobs:
  chrome-test:
    name: Run Chrome tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=chrome" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Commit and push individual report to gh_pages
        if: always()
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh_pages || git checkout gh_pages
          git pull origin gh_pages --rebase
          mkdir -p results-chrome
          cp -r allure-results/* results-chrome/
          git add results-chrome
          git commit -m "Add report for chrome"
          n=0
          until [ $n -ge 5 ]; do
            git pull origin gh_pages --rebase
            git push origin gh_pages && break
            n=$((n+1))
            echo "Push failed, retrying in 3 seconds..."
            sleep 3
          done

          if [ $n -ge 3 ]; then
            echo "Failed to push after 3 attempts."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  edge-test:
    name: Run Edge tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=edge" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Commit and push individual report to gh_pages
        if: always()
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh_pages || git checkout gh_pages
          git pull origin gh_pages --rebase
          mkdir -p results-edge
          cp -r allure-results/* results-edge/
          git add results-edge
          git commit -m "Add report for edge"
          n=0
          until [ $n -ge 3 ]; do
            git pull origin gh_pages --rebase
            git push origin gh_pages && break
            n=$((n+1))
            echo "Push failed, retrying in 3 seconds..."
            sleep 3
          done

          if [ $n -ge 3 ]; then
            echo "Failed to push after 3 attempts."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aggregate:
    name: Generate report
    needs: [ chrome-test, edge-test ]
    if: always()
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Create temp workspace
#        run: mkdir gh_pages
#
#      - name: Download existing gh_pages branch
#        run: |
#          git fetch origin gh_pages
#          git worktree add gh_pages origin/gh_pages

      - name: Checkout gh_pages branch
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo
          ref: gh_pages
          path: gh_pages

      - name: Prepare environment-specific folder
        run: |
          export ENV_NAME=${{ github.event.inputs.environment }}
          export TARGET=gh_pages/$ENV_NAME
          
          echo "Cleaning previous $ENV_NAME folder..."
          rm -rf "$TARGET"
          mkdir -p "$TARGET/allure-results"
          
          echo "Copying Allure test result directories..."
          for dir in gh_pages/results-*; do
            cp -r "$dir"/* "$TARGET/allure-results/" || true
          done
          mkdir -p "$TARGET/allure-results/history"

#      - name: Merge individual reports
#        run: |
#          ls -la gh_pages
#          echo "Removing previous allure-results"
#          sudo rm -rf allure-results
#          sudo rm -rf gh_pages/allure-results
#          mkdir -p gh_pages/allure-results
#          for browser_dir in gh_pages/results-*; do
#            cp -r "$browser_dir"/* gh_pages/allure-results/
#          done
#          mkdir -p gh_pages/allure-results/history
#          echo "Cleaning up results directories"
#          rm -rf gh_pages/results-*
#          ls -la

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh_pages
          allure_history: gh_pages/${{ github.event.inputs.environment }}
          allure_results: gh_pages/${{ github.event.inputs.environment }}/allure-results
          keep_reports: 20

#      - name: Clean up temporary directories
#        run: |
#          echo "Final cleanup of temporary directories"
#          sudo rm -rf gh_pages/allure-results
#          sudo rm -rf gh_pages/results-*
#          sudo rm -rf allure-history
#
#      - name: Remove any nested .git directories to avoid submodules
#        run: |
#          echo "Cleaning any nested .git directories"
#          find gh_pages -type d -name ".git" | xargs rm -rf

      - name: Clean up temporary directories
        run: |
          ls -la
          ls -la gh_pages
          ls -la gh_pages/${{ github.event.inputs.environment }}
          echo "Final cleanup of temporary directories"
          sudo rm -rf gh_pages/allure-results
          sudo rm -rf allure-results
          sudo rm -rf gh_pages/results-*
          sudo rm -rf allure-history/allure-results
          sudo rm -rf allure-history/Common
          sudo rm -rf allure-history/Pages
          sudo rm -rf allure-history/Resources
          sudo rm -rf allure-history/Tests
          sudo rm -rf allure-history/pytest.ini
          sudo rm -rf allure-history/requirements.txt
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/last-history/.git
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/last-history/.github
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/last-history/.gitignore
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/last-history/.idea
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/.git
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/.github
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/.gitignore
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/.idea
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/Common
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/Pages
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/Tests
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/pytest.ini
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/requirements.txt
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/allure-results
          sudo rm -rf gh_pages/${{ github.event.inputs.environment }}/results-*
          sudo rm -rf gh_pages/.git
          sudo rm -rf gh_pages/.github
          sudo rm -rf gh_pages/.gitignore
          sudo rm -rf gh_pages/.idea
          sudo rm -rf gh_pages/Common
          sudo rm -rf gh_pages/Pages
          sudo rm -rf gh_pages/Tests
          sudo rm -rf gh_pages/pytest.ini
          sudo rm -rf gh_pages/requirements.txt
          sudo rm -rf .git
          sudo rm -rf .github
          sudo rm -rf .gitignore
          sudo rm -rf .idea
          sudo rm -rf Common
          sudo rm -rf Pages
          sudo rm -rf Tests
          sudo rm -rf pytest.ini
          sudo rm -rf requirements.txt
          echo "Contents of gh_pages after cleanup:"
          ls -la
          ls -la gh_pages
          ls -la gh_pages/${{ github.event.inputs.environment }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: gh_pages
