name: Run Selenium Tests and publish report experimental

on:
  workflow_dispatch:
    inputs:
      chrome:
        description: 'Include Chrome'
        required: false
        default: true
        type: boolean
      edge:
        description: 'Include Edge'
        required: false
        default: false
        type: boolean

      test_options:
        description: 'Select test options'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Login'
          - 'Logout'

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - 'QA'
          - 'UAT'

jobs:
  chrome-test:
    name: Run Chrome tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=chrome" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Commit and push individual report to gh_pages
        if: always()
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh_pages || git checkout gh_pages
          git pull origin gh_pages --rebase
          mkdir -p results-chrome
          cp -r allure-results/* results-chrome/
          git add results-chrome
          git commit -m "Add report for chrome"
          n=0
          until [ $n -ge 5 ]; do
            git pull origin gh_pages --rebase
            git push origin gh_pages && break
            n=$((n+1))
            echo "Push failed, retrying in 3 seconds..."
            sleep 3
          done

          if [ $n -ge 3 ]; then
            echo "Failed to push after 3 attempts."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  edge-test:
    name: Run Edge tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome == 'true' }}
    environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Set browser variable
        run: echo "BROWSERS=edge" >> "$GITHUB_ENV"

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        env:
          URL: ${{ vars.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BROWSERS: ${{ env.BROWSERS }}
          USERNAME: ${{ vars.USERNAME }}
          CUR_ENV: ${{ vars.CUR_ENV }}

        run: |
          mkdir -p allure-results
          if [ "${{ github.event.inputs.test_options }}" == 'All' ]; then
            pytest
          else
            if [ "${{ github.event.inputs.test_options }}" == 'Login' ]; then
              pytest Tests/test_1_Login.py
            elif [ "${{ github.event.inputs.test_options }}" == 'Logout' ]; then
              pytest Tests/test_2_Logout.py
            else
              echo "Invalid option"
            fi
          fi
        working-directory: .

      - name: Commit and push individual report to gh_pages
        if: always()
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh_pages || git checkout gh_pages
          git pull origin gh_pages --rebase
          mkdir -p results-edge
          cp -r allure-results/* results-edge/
          git add results-edge
          git commit -m "Add report for edge"
          n=0
          until [ $n -ge 3 ]; do
            git pull origin gh_pages --rebase
            git push origin gh_pages && break
            n=$((n+1))
            echo "Push failed, retrying in 3 seconds..."
            sleep 3
          done

          if [ $n -ge 3 ]; then
            echo "Failed to push after 3 attempts."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aggregate:
    name: Generate report
    needs: [ chrome-test, edge-test ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh_pages branch
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/QADemo
          ref: gh_pages
          path: gh_pages

      - name: Install allure
        run: |
          npm install -g allure-commandline

      - name: Clean up test directories
        run: |
          
          sudo rm -rf gh_pages/.git
          sudo rm -rf gh_pages/.github
          sudo rm -rf gh_pages/.gitignore
          sudo rm -rf gh_pages/.idea
          sudo rm -rf gh_pages/Common
          sudo rm -rf gh_pages/Pages
          sudo rm -rf gh_pages/Tests
          sudo rm -rf gh_pages/pytest.ini
          sudo rm -rf gh_pages/requirements.txt

      - name: Define report folder
        id: vars
        run: |
          export ENV_NAME=${{ github.event.inputs.environment }}
          export REPORT_ID=${{ github.run_number }}
          echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "report_id=$REPORT_ID" >> $GITHUB_OUTPUT
          echo "report_path=$ENV_NAME/$REPORT_ID" >> $GITHUB_OUTPUT


      - name: Merge individual reports
        run: |
          ls -la gh_pages
          mkdir -p gh_pages/${{ steps.vars.outputs.report_path }}/allure-results
          for browser_dir in gh_pages/results-*; do
            cp -r "$browser_dir"/* gh_pages/${{ steps.vars.outputs.report_path }}/allure-results/
          done
          echo "Cleaning up results directories"
          rm -rf gh_pages/results-*
          ls -la
          ls -la gh_pages/${{ steps.vars.outputs.report_path }}/allure-results

      - name: Retrieve existing history
        run: |
          if [ -d gh_pages/${{ steps.vars.outputs.env_name }}/last-history ]; then
            mkdir -p gh_pages/${{ steps.vars.outputs.report_path }}/allure-results/history
            cp -r gh_pages/${{ steps.vars.outputs.env_name }}/last-history/* gh_pages/${{ steps.vars.outputs.report_path }}/allure-results/history
          else
            echo "No previous history found. Skipping."
          fi
          
      - name: Generate consolidated Allure report
        run: |
          ls -la gh_pages/${{ steps.vars.outputs.report_path }}/allure-results
          mkdir -p gh_pages/_tmp-report
          allure generate gh_pages/${{ steps.vars.outputs.report_path }}/allure-results --clean -o gh_pages/_tmp-report
          rm -rf gh_pages/${{ steps.vars.outputs.report_path }}/* || true
          mv gh_pages/_tmp-report/* gh_pages/${{ steps.vars.outputs.report_path }}/
          rm -rf gh_pages/_tmp-report

      - name: Patch history-trend.json with report metadata
        run: |
          FILE="gh_pages/${{ steps.vars.outputs.report_path }}/history/history-trend.json"
          REPORT_ID=${{ steps.vars.outputs.report_id }}
          ENV_NAME=${{ steps.vars.outputs.env_name }}
          REPO_NAME="${{ github.event.repository.name }}"
          REPORT_NAME="${ENV_NAME} #${REPORT_ID}"
          REPORT_URL="/${REPO_NAME}/${ENV_NAME}/${REPORT_ID}/index.html"
      
          if [ -f "$FILE" ]; then
            jq --arg name "$REPORT_NAME" \
               --arg url "$REPORT_URL" \
               --argjson order "$REPORT_ID" \
               '.[0] += {reportName: $name, reportUrl: $url, buildOrder: $order}' "$FILE" > tmp.json && mv tmp.json "$FILE"
          else
            echo "No history-trend.json found to patch."
          fi

      - name: Save last history
        run: |
          if [ ! -d gh_pages/${{ steps.vars.outputs.env_name }}/last-history ]; then
            mkdir -p gh_pages/${{ steps.vars.outputs.env_name }}/last-history
          fi
          cp -r gh_pages/${{ steps.vars.outputs.report_path }}/history/* gh_pages/${{ steps.vars.outputs.env_name }}/last-history

      - name: Create environment-level index.html redirect
        run: |
          ENV_NAME=${{ steps.vars.outputs.env_name }}
          REPORT_ID=${{ steps.vars.outputs.report_id }}
          INDEX_PATH="gh_pages/$ENV_NAME/index.html"
      
          echo "Creating index.html to redirect to latest report: $REPORT_ID"
          cat > "$INDEX_PATH" <<EOF
          <!DOCTYPE html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; URL=https://Simeon-Zografov.github.io/QADemo/$ENV_NAME/$REPORT_ID/index.html">
          <meta http-equiv="Pragma" content="no-cache">
          <meta http-equiv="Expires" content="0">
          EOF
      
          echo "Generated index.html:"
          cat "$INDEX_PATH"

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: gh_pages
